# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  versionPrefix: 0.1.1
  buildConfiguration: Release

name: $(versionPrefix).$(Build.BuildId)

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.0.x'
  inputs:
    version: '3.0.x'


- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) /warnaserror'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Pack projects"
  inputs:
    command: 'pack'
    versioningScheme: byBuildNumber
    projects: 'src/**/*.csproj'

- task: NuGetCommand@2
  displayName: "Publish to NuGet"
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    publishFeedCredentials: NuGet
    allowPackageConflicts: true
